In [1]:
# import numpy package as np
import numpy as np

In [9]:
#1
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.intersect1d(a, b)
print(c)

[2 4]


first assigning a and b to arrays. then use np.intersectld function to find the distinct value and assign to c, then print

In [8]:
#2
a = np.arange(1,16).reshape(3,5).T
print(a)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


first use np.arange to create array from 1 to 15, then reshape function to reshape the array in to '3rows and 5 columns'， finally followed with'.t' to transite the array in to '5 rows and 3 columns' array and print

In [10]:
#3
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
c = np.intersect1d(a, b)
for i in range(len(c)):
    a = a[a!=c[i]]
print(a)

[ 7 15  1  8]


first assigning a and b to arrays, when use np.intersectld to find the distinct value in a and b, and assign to C
then use an interation to remove any elements c from a. then print

In [36]:
#4
a=np.random.randint(1,1553,31)
a= np.append(a, (a[8], a[16], a[20], a[25]))
a= np.sort(a)
a[34]=1553
print('CUMULATIVE MILES:', a)

b = np.diff(a)
c = np.append(a[0],b)
print('Daily:',c)

CUMULATIVE MILES: [  39  112  142  181  187  284  334  387  416  425  499  544  613  771
  772  772  777  820  823  823  898  935  935  940 1027 1217 1265 1300
 1316 1366 1381 1412 1440 1447 1553]
Daily: [ 39  73  30  39   6  97  50  53  29   9  74  45  69 158   1   0   5  43
   3   0  75  37   0   5  87 190  48  35  16  50  15  31  28   7 106]


first use np.random.randint to generate random number from 1 to 1553 for 31 days and assig to a，
then deside 8,16,20,25 not miles, use append. function to add same cumulated miles into a，
sort the array with np.sort
make sure the last day is 1553 miles till key west
print

np.diff(a) to get the different in array,
a[0] is first day miles so, and use np.append function to append b
print

In [ ]:
#5
import pandas
import numpy as np
